//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppWarcraftFriends.ServiceReferenceCharacter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailUrlField;
        
        private bool MainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Faction {
            get {
                return this.FactionField;
            }
            set {
                if ((object.ReferenceEquals(this.FactionField, value) != true)) {
                    this.FactionField = value;
                    this.RaisePropertyChanged("Faction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Realm {
            get {
                return this.RealmField;
            }
            set {
                if ((object.ReferenceEquals(this.RealmField, value) != true)) {
                    this.RealmField = value;
                    this.RaisePropertyChanged("Realm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ThumbnailUrl {
            get {
                return this.ThumbnailUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailUrlField, value) != true)) {
                    this.ThumbnailUrlField = value;
                    this.RaisePropertyChanged("ThumbnailUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Main {
            get {
                return this.MainField;
            }
            set {
                if ((this.MainField.Equals(value) != true)) {
                    this.MainField = value;
                    this.RaisePropertyChanged("Main");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCharacter.MicroServiceCharacterSoap")]
    public interface MicroServiceCharacterSoap {
        
        // CODEGEN: Generating message contract since element name region from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCharacterDetails", ReplyAction="*")]
        WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse GetCharacterDetails(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCharacterDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse> GetCharacterDetailsAsync(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCharacterDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCharacterDetails", Namespace="http://tempuri.org/", Order=0)]
        public WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequestBody Body;
        
        public GetCharacterDetailsRequest() {
        }
        
        public GetCharacterDetailsRequest(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCharacterDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string realm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        public GetCharacterDetailsRequestBody() {
        }
        
        public GetCharacterDetailsRequestBody(string region, string realm, string name) {
            this.region = region;
            this.realm = realm;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCharacterDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCharacterDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponseBody Body;
        
        public GetCharacterDetailsResponse() {
        }
        
        public GetCharacterDetailsResponse(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCharacterDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebAppWarcraftFriends.ServiceReferenceCharacter.Character GetCharacterDetailsResult;
        
        public GetCharacterDetailsResponseBody() {
        }
        
        public GetCharacterDetailsResponseBody(WebAppWarcraftFriends.ServiceReferenceCharacter.Character GetCharacterDetailsResult) {
            this.GetCharacterDetailsResult = GetCharacterDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MicroServiceCharacterSoapChannel : WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MicroServiceCharacterSoapClient : System.ServiceModel.ClientBase<WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap>, WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap {
        
        public MicroServiceCharacterSoapClient() {
        }
        
        public MicroServiceCharacterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MicroServiceCharacterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MicroServiceCharacterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MicroServiceCharacterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap.GetCharacterDetails(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest request) {
            return base.Channel.GetCharacterDetails(request);
        }
        
        public WebAppWarcraftFriends.ServiceReferenceCharacter.Character GetCharacterDetails(string region, string realm, string name) {
            WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest inValue = new WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest();
            inValue.Body = new WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequestBody();
            inValue.Body.region = region;
            inValue.Body.realm = realm;
            inValue.Body.name = name;
            WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse retVal = ((WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap)(this)).GetCharacterDetails(inValue);
            return retVal.Body.GetCharacterDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse> WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap.GetCharacterDetailsAsync(WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest request) {
            return base.Channel.GetCharacterDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsResponse> GetCharacterDetailsAsync(string region, string realm, string name) {
            WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest inValue = new WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequest();
            inValue.Body = new WebAppWarcraftFriends.ServiceReferenceCharacter.GetCharacterDetailsRequestBody();
            inValue.Body.region = region;
            inValue.Body.realm = realm;
            inValue.Body.name = name;
            return ((WebAppWarcraftFriends.ServiceReferenceCharacter.MicroServiceCharacterSoap)(this)).GetCharacterDetailsAsync(inValue);
        }
    }
}
